-- Create security_reports table in Supabase
CREATE TABLE IF NOT EXISTS security_reports (
  id SERIAL PRIMARY KEY,
  scan_id VARCHAR(255) UNIQUE NOT NULL,
  company_name VARCHAR(255) NOT NULL,
  report_content TEXT NOT NULL,
  executive_summary TEXT,
  generated_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_security_reports_scan_id ON security_reports(scan_id);
CREATE INDEX IF NOT EXISTS idx_security_reports_company ON security_reports(company_name);
CREATE INDEX IF NOT EXISTS idx_security_reports_created_at ON security_reports(created_at);

-- Enable Row Level Security (optional)
ALTER TABLE security_reports ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all operations for now (adjust as needed)
CREATE POLICY "Allow all operations on security_reports" ON security_reports
FOR ALL USING (true) WITH CHECK (true);

-- Add comments
COMMENT ON TABLE security_reports IS 'Stores generated security due diligence reports';
COMMENT ON COLUMN security_reports.scan_id IS 'Unique identifier for the security scan';
COMMENT ON COLUMN security_reports.company_name IS 'Name of the company that was scanned';
COMMENT ON COLUMN security_reports.report_content IS 'Full security assessment report content';
COMMENT ON COLUMN security_reports.executive_summary IS 'Executive summary for C-suite audience';
COMMENT ON COLUMN security_reports.generated_at IS 'Timestamp when the report was generated by AI';

-- Show table info
\d security_reports; 