steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/dealbrief/scanner-worker:latest', '.']

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/dealbrief/scanner-worker:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'scanner-service'
      - '--image'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/dealbrief/scanner-worker:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '600'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--concurrency'
      - '1'
      - '--service-account'
      - 'scanner-worker-sa@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'RUNTIME_MODE=gcp,NODE_ENV=production'

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/dealbrief/scanner-worker:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'